# 01-Homework: Introduction

In [63]:
import pandas as pd
import numpy as np

## Question 1

In [2]:
pd.__version__

'2.2.2'

## Question 2

In [3]:
data = pd.read_csv('laptops.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [4]:
data.shape

(2160, 12)

## Question 3

In [5]:
data.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [6]:
laptop_brands = data['Brand'].unique()

In [7]:
print(laptop_brands)

['Asus' 'Alurin' 'MSI' 'HP' 'Lenovo' 'Medion' 'Acer' 'Apple' 'Razer'
 'Gigabyte' 'Dell' 'LG' 'Samsung' 'PcCom' 'Microsoft' 'Primux' 'Prixton'
 'Dynabook Toshiba' 'Thomson' 'Denver' 'Deep Gaming' 'Vant' 'Innjoo'
 'Jetwing' 'Millenium' 'Realme' 'Toshiba']


In [9]:
print(f'Number of unique laptop brands: {len(laptop_brands)}')

Number of unique laptop brands: 27


## Question 4. Missing values

In [17]:
data.describe(include = 'all')

Laptop Status Brand Model  \
count                                                2160   2160  2160  2160   
unique                                               2160      2    27   121   
top     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New  Asus   15S   
freq                                                    1   1498   415   115   
mean                                                  NaN    NaN   NaN   NaN   
std                                                   NaN    NaN   NaN   NaN   
min                                                   NaN    NaN   NaN   NaN   
25%                                                   NaN    NaN   NaN   NaN   
50%                                                   NaN    NaN   NaN   NaN   
75%                                                   NaN    NaN   NaN   NaN   
max                                                   NaN    NaN   NaN   NaN   

                  CPU          RAM      Storage Storage type       GPU  \
count            2160  2160.000000  2160.000000         2118       789   
unique             28          NaN          NaN            2        44   
top     Intel Core i7          NaN          NaN          SSD  RTX 3050   
freq              710          NaN          NaN         2062       129   
mean              NaN    15.413889   596.294444          NaN       NaN   
std               NaN     9.867815   361.220506          NaN       NaN   
min               NaN     4.000000     0.000000          NaN       NaN   
25%               NaN     8.000000   256.000000          NaN       NaN   
50%               NaN    16.000000   512.000000          NaN       NaN   
75%               NaN    16.000000  1000.000000          NaN       NaN   
max               NaN   128.000000  4000.000000          NaN       NaN   

             Screen Touch  Final Price  
count   2156.000000  2160  2160.000000  
unique          NaN     2          NaN  
top             NaN    No          NaN  
freq            NaN  1933          NaN  
mean      15.168112   NaN  1312.638509  
std        1.203329   NaN   911.475417  
min       10.100000   NaN   201.050000  
25%       14.000000   NaN   661.082500  
50%       15.600000   NaN  1031.945000  
75%       15.600000   NaN  1708.970000  
max       18.000000   NaN  7150.470000

In [29]:
columns_with_missing = data.columns[data.isnull().any()].tolist()
print(f'Number of missing columns: {len(columns_with_missing)}')

Number of missing columns: 3


## Question 5. Maximum final price

In [22]:
dell_laptops = data[data['Brand'] == 'Dell']

In [24]:
print(f"Maximum final prize is for Dell: {dell_laptops['Final Price'].max()}")

Maximum final prize is for Dell: 3936.0


## Question 6. Median value of Screen

In [37]:
screen_median = data["Screen"].median()
print(f'Median value of screen: {screen_median}')

Median value of screen: 15.6


In [46]:
screen_mode = data["Screen"].mode()
print(f'Most frequent value of screen: {screen_mode[0]}')

Most frequent value of screen: 15.6


In [51]:
screen_filled = data["Screen"].fillna(15.6)
screen_median = data["Screen"].median()
print(f'Median value of screen: {screen_median}')

Median value of screen: 15.6


## Question 7. Sum of weights

Select all the "Innjoo" laptops from the dataset.

In [53]:
injoo_laptops = data[data['Brand'] == 'Innjoo']

Select only columns RAM, Storage, Screen

In [54]:
injoo_laptops = injoo_laptops[['RAM', 'Storage', 'Screen']]
injoo_laptops.head()

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1

Get the underlying NumPy array. Let's call it X

In [59]:
X = injoo_laptops.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [61]:
XTX = X.T@X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

Compute the inverse of XTX

In [64]:
inverse_XTX = np.linalg.inv(XTX)
inverse_XTX

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

In [66]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [69]:
w = inverse_XTX@X.T
w = w@y
w

array([45.58076606,  0.42783519, 45.29127938])

What's the sum of all the elements of the result?

In [70]:
sum(w)

91.29988062995588